### ISSUE TITLE
Swift 3 stable

### ISSUE THREAD

**Issue by tamastimar** [SwiftDocOrg/swiftdoc-parser#10]
Could you please update the site with the docset of Swift 3 stable?

Thanks for your work, the site is very useful! 👍

**Comment by tamastimar** [comment]
Thanks for SwiftDocOrg/SwiftDocOrg.github.io@6cf14f0fa0cdaa7a2b6d2fa46baa06bba0285c7f.

**Comment by natecook1000** [comment]
Thanks!
