### ISSUE TITLE
node-gyp issues when running npm install

### ISSUE THREAD

**Issue by hackin247** [SwiftDocOrg/swiftdoc-parser#11]
I upgraded node and npm but still no go.   Partial capture of error message below.

`make: *** [Release/obj.target/shell/execsync.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.3.0
gyp ERR! command "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jchulani/Developer/tools/swiftdoc-parser/node_modules/execsyncs
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! execsyncs@0.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the execsyncs@0.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the execsyncs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs execsyncs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls execsyncs
npm ERR! There is likely additional logging output above.`

**Comment by mdiep** [comment]
I'm seeing this too and don't know anything about how to resolve it. 😐

**Comment by mattt** [comment]
Apologies for the late response on this, @hackin247  and @mdiep. I wasn't able to resolve this either, and this is ultimately what prompted me to write [swift-doc](https://github.com/SwiftDocOrg/swift-doc) as a replacement. The good news is that this new tool is written in Swift, so our days of wrangling `node_modules` are (thankfully) behind us.
