### ISSUE TITLE
Enable parsing of headers from third-party Swift frameworks

### ISSUE THREAD

**Issue by kareman** [SwiftDocOrg/swiftdoc-parser#2]
When I try to parse [this header](https://gist.github.com/kareman/3d8027809b4cd1364c5c) I get the error message `Error: couldn't find 'NSFileHandle' for extension.`. If I add empty declarations for all the types the parser can't find, like so:

```swift
class NSFileHandle {}

struct String {}

protocol Streamable {}
protocol OutputStreamType {}
```

I get the error message 

```

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:904:11)
    at Object.afterWrite (net.js:720:19)
```

**Comment by natecook1000** [comment]
That should parse properly now without added fake declarations. The extensions will have a "kind" of "extension", which isn't supported in the downstream documentation building yet, but you should be able to get the JSON output now.

If you do want the fake declarations, so you end up with the correct `struct` vs `class` vs `protocol`, I think you probably need a line break between the opening and closing braces. The parser has only been tested with one input source, so it has some brittle places -- I'll add that as a new issue.

**Comment by kareman** [comment]
Yes when I leave the fake declarations out and ask for only JSON output I get the following:

```
Note: extension for undeclared class "NSFileHandle".
Note: extension for undeclared class "String".
Note: In "ReadableStreamType", can't find "Streamable".
Note: In "WriteableStreamType", can't find "OutputStreamType".
```

Followed by the JSON output.

But when I put the declarations back in, with line breaks between the curly braces [like this](https://gist.github.com/kareman/3d8027809b4cd1364c5c) and try to build the documentation I get the following error message:

```

swiftdoc-builder.js: 336
        outputHTML('operator/' + convertOperatorName(el.name), templates.opera
                                 ^
ReferenceError: convertOperatorName is not defined
    at /Users/karemorstol/Data/lib/swiftdoc-parser/lib/swiftdoc-builder.js:336:34
    at Array.forEach (native)
    at build (/Users/karemorstol/Data/lib/swiftdoc-parser/lib/swiftdoc-builder.js:335:23)
    at Object.<anonymous> (/Users/karemorstol/Data/lib/swiftdoc-parser/index.js:68:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

When I ask for only JSON everything looks fine. No error messages.

**Comment by natecook1000** [comment]
@kareman, thanks for reporting back -- can give this another try? I should be correctly handling those issues now.

**Comment by kareman** [comment]
Not sure what I'm doing wrong here, but I can't get this to work. It builds JSON fine, but when I try building the HTML I get the same error message as in the first post. This is with or without the fake declarations, it even happens with test/data/ok.text :

```
admins-iMac:swiftdoc-parser admin$ node ./index.js  test/data/ok.txt 

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:905:11)
    at Object.afterWrite (net.js:721:19)
```

I also tried a fresh download and install of Node.JS plus this parser in a Mavericks VM, but with the same results.

**Comment by natecook1000** [comment]
Ah! Do you have Graphviz installed? The script looks for `dot` at `/usr/local/bin/dot`, and it looks like it crashes if you don't have it. I'll add an option to turn off graph generation—in the meantime, you can get Graphviz from here: http://www.graphviz.org/Download.php

**Comment by kareman** [comment]
No I don't have that. I'll install it and test again when I get back on Monday. 
Maybe there could be an install-script that installs it along with all the Node-modules?

**Comment by kareman** [comment]
I see Graphviz is mentioned in the README, sorry about that. But now it is installed, and when I run the parser with an empty output directory it says:

```
fs: missing callback Error: ENOENT, open './output/assets/js/swift-linkdata.js'
```

The file it refers to does not exist. If I run it again there are no errors, and "/assets/js/swift-linkdata.js" is present.

To get Jekyll to serve the site locally I copied the following files/folders from https://github.com/SwiftDocOrg/SwiftDoc.org to the output folder:

_assets
_config.yml
_includes
_layouts
_plugins
_posts
404.md
Procfile

And edited _config.yml. Jekyll then required me to install the gems japr, less and therubyracer. Now when I run `jekyll serve` I get 2 warnings:

```
/Users/karemorstol/Data/lib/swiftdoc-parser/output/_plugins/archive_gen.rb:72: warning: already initialized constant Jekyll::MonthlyArchivePage::ATTRIBUTES_FOR_LIQUID
/Users/karemorstol/Data/lib/swiftdoc-parser/output/_plugins/_site/archive_gen.rb:72: warning: previous definition of ATTRIBUTES_FOR_LIQUID was here
```

But apart from that it seems to be working fine. I can now browse my documentation locally. Excellent.

**Comment by natecook1000** [comment]
I've updated the instructions to use bundler in the swiftdoc.org repo — should help with these dependencies in the future. Thanks!
