### ISSUE TITLE
Building error on `SinkType`

### ISSUE THREAD

**Issue by norio-nomura** [SwiftDocOrg/swiftdoc-parser#4]
http://swiftdoc.org/protocol/SinkType/

Original:
```swift
///   func f(g: (X)->Void) { ... g(a) ...}
///
/// the following generates better code::
```
is converted to:
```
| func f(g: (X)->Void) { .**g(a) ...}
 the following generates better code:**
```
Maybe it caused by following:
https://github.com/SwiftDocOrg/swiftdoc-parser/blob/master/lib%2Fswiftdoc-builder.js#L106
```javascript
                .replace(/\.\. ([^:]+)::/g, '**$1:**')       // incorrect format for inline header?
```
Is excluding line ending needed?

**Comment by natecook1000** [comment]
@norio-nomura, that was exactly the issue! This was causing issue #1 as well, but I had just never dug in to debug it. Thanks so much! :+1:

**Comment by norio-nomura** [comment]
I confirmed that this issue has been resolved. :+1: 
Thank you so much for creating SwiftDoc.org.
