### ISSUE TITLE
Spelling error - iff

### ISSUE THREAD

**Issue by proyb6** [SwiftDocOrg/swiftdoc-parser#8]
http://swiftdoc.org/v2.2/type/AnyBidirectionalCollection/#func-contains_

Returns true iff an element in self satisfies predicate.

**Comment by natecook1000** [comment]
Hi @proyb6! "iff" is short for "if and only if"—it's a tighter constraint on what comes after. FWIW, those comments come directly from the Swift standard library's generated header. There's no editing of those at all.
