### ISSUE TITLE
Cannot run index.js

### ISSUE THREAD

**Issue by huy-le** [SwiftDocOrg/swiftdoc-parser#9]
I follow the instruction. Choose node v0.10. Then `npm install`. 

But when I type `./index.js --help` it fails.

<img width="696" alt="screen shot 2016-07-21 at 11 30 17 am" src="https://cloud.githubusercontent.com/assets/3965573/17008676/d4bf603e-4f36-11e6-981c-4e38323d61b9.png">

**Comment by arthurhammer** [comment]
Same issue here.

**Comment by mattt** [comment]
Apologies for the late response on this, @huy-le  and @arthurhammer. I wasn't able to resolve this either, and this is ultimately what prompted me to write [swift-doc](https://github.com/SwiftDocOrg/swift-doc) as a replacement. The good news is that this new tool is written in Swift, so our days of wrangling `node_modules` are (thankfully) behind us.
